name: Generate Snake

on:
  schedule: 
    - cron: "0 */12 * * *" # roda a cada 12h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: v-anjos
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
